#!/usr/bin/env bash
#
# Generate the beam-counter reference table from Copperline.
#
# WHY THIS EXISTS. docs/core-accuracy-todo.md opens by saying we cannot measure
# against real hardware, and T7 -- "characterise what the beam counter still
# gets wrong" -- has sat at [SUITE] ever since, meaning it needs a MiSTer, a
# screen and a person reading it. Copperline is not hardware either, but it is
# an independently written cycle-driven model with a machine-readable interface,
# which is a second opinion we have never had. This turns T7 from an errand into
# a diff.
#
# WHAT IT PRODUCES. rtl/sim/beamcounter/beam-reference.tsv: one row per sampled
# beam position, recording the beam state and what VPOSR/VHPOSR read there.
# rtl/sim/beamcounter/tb_beamcounter_reference.sv checks our RTL against it in
# CI, so CI never needs Copperline -- only regenerating the table does.
#
# WHAT THE TABLE IS NOT. It is not ground truth. Copperline is a third
# implementation, not silicon; where it and our RTL disagree that is a question,
# not a verdict. The bench is written accordingly: it pins how many rows agree
# today and fails when that number MOVES, in either direction. A drop is a
# regression; a rise is progress that should be recorded rather than silently
# banked.
#
# USAGE
#   tools/copperline-beamtable.sh /path/to/copperline-checkout [MODEL]
#
# Needs a release build of Copperline in that checkout
# (cargo build --release --bin copperline --bin copperline-ctl; needs rustc
# 1.95+, libudev-dev and libasound2-dev -- all three were fatal when absent).
# No ROMs: Copperline boots its bundled AROS, and the beam counter runs
# regardless of what the guest is doing.

set -euo pipefail
cd "$(dirname "$0")/.."

CANON="${1:?usage: copperline-beamtable.sh /path/to/copperline [MODEL]}"
MODEL="${2:-A500}"
OUT="rtl/sim/beamcounter/beam-reference.tsv"

CL="$CANON/target/release/copperline"
CTL="$CANON/target/release/copperline-ctl"
for f in "$CL" "$CTL"; do
    [ -x "$f" ] || { echo "error: $f not found -- build Copperline first" >&2; exit 1; }
done

INFO="$(mktemp -d)/ccp.json"
"$CL" --factory --model "$MODEL" --noaudio --control :0 --control-info "$INFO" \
      >"$(dirname "$INFO")/emu.log" 2>&1 &
EMU=$!
trap 'kill $EMU 2>/dev/null || true' EXIT

# The server writes the info file once it is listening; there is no other
# handshake, so poll for it rather than sleeping a guessed interval.
for _ in $(seq 1 120); do [ -s "$INFO" ] && break; sleep 0.5; done
[ -s "$INFO" ] || { echo "error: Copperline control server did not start" >&2; exit 1; }

VER="$("$CL" --version 2>/dev/null | head -1 || echo unknown)"
REV="$(git -C "$CANON" rev-parse --short HEAD 2>/dev/null || echo unknown)"

{
  echo "# Beam-counter reference, generated by tools/copperline-beamtable.sh"
  echo "# source   = $VER ($REV), --model $MODEL --factory"
  echo "# generated= $(date -u +%Y-%m-%d)"
  echo "#"
  echo "# Columns are one instant each, read with the machine stopped:"
  echo "#   vpos,hpos  Copperline's internal beam position (beam.get). hpos is"
  echo "#              in COLOUR CLOCKS. Ours is [8:0] at 140ns with hpos[0] as"
  echo "#              the cck phase, so ours maps as hpos[8:1]."
  echo "#   vposr      custom.read 0x004 -- a debugger peek, not a CPU bus read,"
  echo "#              so it carries no CPU-read cost. That is deliberate: it"
  echo "#              makes it comparable to our combinational data_out."
  echo "#   vhposr     custom.read 0x006"
  echo "#   dhpos      vhposr[7:0] - hpos, signed. Constant across the table on"
  echo "#              the side that generated it; our RTL reports hpos[8:1]-1"
  echo "#              (the 06f30af decrement). The ABSOLUTE value is not"
  echo "#              comparable between implementations -- neither internal"
  echo "#              counter's zero point is a shared reference -- so the"
  echo "#              bench checks that it is CONSTANT, not what it equals."
  echo "#   vok        vhposr[15:8] == vpos & 0xFF     (1 = readback agrees)"
  echo "#   pok        vposr[0]      == vpos[8]        (1 = readback agrees)"
  echo "#"
  echo "# vok/pok are the origin-INDEPENDENT columns, and the reason this table"
  echo "# is worth having. They ask only whether the readback describes the beam"
  echo "# position it was taken at, which both implementations can be asked"
  echo "# without agreeing on anything first. A zero marks a readback lag --"
  echo "# exactly what T7 is chasing."
  echo "#"
  printf "vpos\thpos\tvposr\tvhposr\tdhpos\tvok\tpok\n"
} > "$OUT"

# Rows accumulate here and are deduped into $OUT at the end: run_until stops at
# INSTRUCTION resolution, not colour-clock resolution, so a sweep that asks for
# consecutive cck values gets the same position back several times over. The
# duplicates carry no information and would make the table look finer-grained
# than the instrument is.
RAW="$(mktemp)"
trap 'kill $EMU 2>/dev/null || true; rm -f "$RAW"' EXIT

sample() {   # the machine is already stopped where we want it
    local B P H
    B="$("$CTL" --info "$INFO" beam.get)"
    P="$("$CTL" --info "$INFO" custom.read '{"reg":"0x004"}')"
    H="$("$CTL" --info "$INFO" custom.read '{"reg":"0x006"}')"
    python3 tools/copperline-beamrow.py "$B" "$P" "$H" >> "$RAW"
}

rows=0

# Coarse: one sample per sampled line, across a whole frame.
for V in $(seq 0 4 312); do
    "$CTL" --info "$INFO" run_until "{\"vpos\":$V}" >/dev/null 2>&1 || continue
    sample
    rows=$((rows + 1))
done

# Fine: every colour clock across the frame wrap. The vertical readback lag is
# a SUB-LINE effect, so one sample per line cannot measure how wide it is -- and
# the width is the interesting number, because our own RTL delays vpos by two
# clk7_en stages (vpos -> vpos_d1 -> vpos_rb) before VPOSR reports it. Two
# lines' worth of colour clocks covers the wrap with room either side.
CK="$("$CTL" --info "$INFO" run_until '{"vpos":311}' 2>/dev/null \
      | python3 -c 'import json,sys; print(json.load(sys.stdin)["result"]["cck"])')"
if [ -n "${CK:-}" ]; then
    for i in $(seq 0 480); do
        "$CTL" --info "$INFO" run_until "{\"cck\":$((CK + i))}" >/dev/null 2>&1 || continue
        sample
        rows=$((rows + 1))
    done
fi

# One row per distinct beam position, order preserved.
awk '!seen[$1 "\t" $2]++' "$RAW" >> "$OUT"
kept=$(awk '!/^#/ && NF' "$RAW" | awk '!s[$1 "\t" $2]++' | wc -l)

# The achieved resolution is a property of the run, not a constant, so measure
# it rather than asserting it: the median gap between consecutive sampled hpos
# values within a line is how close together two samples actually landed.
res=$(awk -F'\t' 'p1==$1 && $2>p2 {print $2-p2} {p1=$1; p2=$2}' "$OUT" \
      | sort -n | awk '{v[NR]=$1} END {if (NR) print v[int((NR+1)/2)]; else print "?"}')
sed -i "s|^# generated= .*|&\n#\n# Sampling resolution: run_until stops at INSTRUCTION resolution, not colour\n# clock resolution, so positions come at roughly every ${res} colour clocks and a\n# lag narrower than that is BOUNDED by this table, not pinned by it. Reading a\n# register at cck resolution needs a guest polling loop (what the vAmigaTS VPOS\n# suite and timing-test rows 16/17/21 do), not the debugger.|" "$OUT"

echo "wrote $OUT ($kept distinct positions from $rows samples, $MODEL, ~${res} cck resolution)"
